# Generated by Django 5.0.4 on 2024-09-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_remove_actor_fun_fact_remove_actor_weight'),
        ('users', '0004_profile_following_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='movies.movie'),
        ),
    ]
