# Generated by Django 5.0.4 on 2024-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0047_alter_role_character'),
        ('users', '0005_profile_watched_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('movies', models.ManyToManyField(blank=True, related_name='lists', to='movies.movie')),
                ('profile', models.ManyToManyField(related_name='lists', to='users.profile')),
            ],
        ),
    ]
