# Generated by Django 5.0.4 on 2024-11-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0047_alter_role_character'),
        ('users', '0006_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('movies', models.ManyToManyField(blank=True, related_name='lists', to='movies.movie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
