# Generated by Django 5.0.4 on 2024-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customlist_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
