# Generated by Django 5.0.4 on 2024-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='privacy',
            field=models.TextField(choices=[('friends', 'Friends'), ('everyone', 'Everyone'), ('only_me', 'Only Me')], default='everyone'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='ranked_list',
            field=models.BooleanField(default=False),
        ),
    ]
