# Generated by Django 5.0.4 on 2024-11-14 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customlist_privacy_customlist_ranked_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
