# Generated by Django 5.0.4 on 2024-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customlist_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default.jfif', upload_to='media'),
        ),
    ]
