# Generated by Django 5.1.4 on 2025-01-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
