# Generated by Django 5.0.4 on 2024-07-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.ImageField(upload_to='media'),
        ),
    ]
