# Generated by Django 5.0.4 on 2024-08-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
