# Generated by Django 5.0.4 on 2024-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_hours_movie_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='media/default.jfif', upload_to='media'),
        ),
    ]
