# Generated by Django 5.0.4 on 2024-08-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_review_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='media/default.jfif', upload_to='media')),
                ('movies', models.ManyToManyField(to='movies.movie')),
            ],
        ),
    ]
