# Generated by Django 5.0.4 on 2024-08-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(related_name='director', to='movies.movie'),
        ),
    ]
