# Generated by Django 5.0.4 on 2024-08-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_director_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(related_name='directors', to='movies.movie'),
        ),
    ]
