# Generated by Django 5.0.4 on 2024-08-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_actor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='bio',
            field=models.TextField(default='No bio yet.'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.TextField(default='No bio yet.'),
        ),
    ]
