# Generated by Django 5.0.4 on 2024-08-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_movievideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movievideo',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movies.movie'),
        ),
    ]
