# Generated by Django 5.0.4 on 2024-08-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_movievideo_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movievideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
