# Generated by Django 5.0.4 on 2024-08-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_award'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
    ]
