# Generated by Django 5.0.4 on 2024-08-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_name',
            field=models.CharField(choices=[('Academy Award', 'Academy Award'), ('Golden Globe', 'Golden Globe'), ('BAFTA', 'BAFTA'), ('Emmy Award', 'Emmy Award')], default='Academy Award', max_length=50),
        ),
    ]
