# Generated by Django 5.0.4 on 2024-08-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_award_award_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('Best Picture', 'Best Picture'), ('Best Director', 'Best Director'), ('Best Actor', 'Best Actor'), ('Best Actress', 'Best Actress'), ('Best Supporting Actor', 'Best Supporting Actor'), ('Best Supporting Actress', 'Best Supporting Actress'), ('Best Cinematography', 'Best Cinematography'), ('Best Film Editing', 'Best Film Editing'), ('Best Production Design', 'Best Production Design'), ('Best Costume Design', 'Best Costume Design'), ('Best Makeup and Hairstyling', 'Best Makeup and Hairstyling'), ('Best Visual Effects', 'Best Visual Effects'), ('Best Original Score', 'Best Original Score'), ('Best Sound', 'Best Sound'), ('Best Animated Feature', 'Best Animated Feature')], default='Best Picture', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default='No overview yet'),
        ),
    ]
