# Generated by Django 5.0.4 on 2024-09-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='actor',
            name='birth_place',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], default='Not specified', max_length=1),
        ),
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
