# Generated by Django 5.0.4 on 2024-09-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_actor_birth_date_actor_birth_place_actor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='fun_fact',
            field=models.TextField(default='No fun facts added yet'),
        ),
        migrations.AddField(
            model_name='actor',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actor',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
