# Generated by Django 5.0.4 on 2024-09-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_actor_fun_fact_actor_height_actor_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='fun_fact',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='weight',
        ),
    ]
