# Generated by Django 5.0.4 on 2024-10-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_remove_actor_fun_fact_remove_actor_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='director',
            name='birth_place',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], default='Not specified', max_length=1),
        ),
        migrations.AddField(
            model_name='director',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='nationality',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
