# Generated by Django 5.0.4 on 2024-10-13 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_personimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.personimage'),
        ),
        migrations.AddField(
            model_name='director',
            name='director_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.personimage'),
        ),
    ]
