# Generated by Django 5.0.4 on 2024-10-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_actor_actor_images_director_director_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_images',
        ),
        migrations.RemoveField(
            model_name='director',
            name='director_images',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_images',
            field=models.ManyToManyField(blank=True, null=True, to='movies.personimage'),
        ),
        migrations.AddField(
            model_name='director',
            name='director_images',
            field=models.ManyToManyField(blank=True, null=True, to='movies.personimage'),
        ),
    ]
