# Generated by Django 5.0.4 on 2024-10-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_remove_actor_actor_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_images',
            field=models.ManyToManyField(blank=True, related_name='actors', to='movies.personimage'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_images',
            field=models.ManyToManyField(blank=True, related_name='directors', to='movies.personimage'),
        ),
    ]
