# Generated by Django 5.0.4 on 2024-10-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0038_remove_actor_actor_images_actor_actor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_image',
        ),
        migrations.RemoveField(
            model_name='director',
            name='director_images',
        ),
    ]
