# Generated by Django 5.0.4 on 2024-10-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0039_remove_actor_actor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='images',
            field=models.ManyToManyField(related_name='actors', to='movies.personimage'),
        ),
    ]
