# Generated by Django 5.0.4 on 2024-10-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0040_actor_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieimage',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movie_images', to='movies.actor'),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='movie_images', to='movies.director'),
        ),
    ]
