# Generated by Django 5.0.4 on 2024-10-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0041_movieimage_actors_movieimage_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='actors', to='movies.personimage'),
        ),
    ]
