# Generated by Django 5.0.4 on 2024-11-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0044_alter_role_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='character_name',
            field=models.CharField(max_length=100),
        ),
    ]
