# Generated by Django 5.0.4 on 2024-11-03 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0046_character_remove_role_character_name_role_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='movies.character'),
        ),
    ]
