# Generated by Django 5.1.4 on 2025-01-16 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0047_alter_role_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
