# Generated by Django 5.1.4 on 2025-01-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0050_review_unique_user_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='has_spoilers',
            field=models.BooleanField(default=False),
        ),
    ]
